version: "3"

services:
  code-server:
    image: linuxserver/code-server:latest
    container_name: VScode
    restart: unless-stopped
    ports:
      - 8443:8443
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - PASSWORD=${PASSWORD}
      - SUDO_PASSWORD=${SUDO_PASSWORD}
      # - PROXY_DOMAIN=code-server.my.domain #optional
      - DEFAULT_WORKSPACE=/workspace #current directory
    volumes:
      - ./config:/config
      - ../:/workspace