version: "3"

services:
  pihole:
    image: pihole/pihole:latest
    container_name: Pi-Hole
    restart: always
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "5353:80/tcp"
    volumes:
      - "pihole-data:/etc/pihole"
      - "dnsmasq.d-data:/etc/dnsmasq.d"
    environment:
      TZ: "Europe/Berlin"
      WEBPASSWORD: ${WEBPASSWORD}

volumes:
  pihole-data:
  dnsmasq.d-data: