version: "3"

services:
  duplicati:
    image: linuxserver/duplicati:latest
    container_name: Duplicati
    restart: unless-stopped
    ports:
      - 8200:8200
    environment:
      - PUID=0 # root
      - PGID=0
      - TZ=Europe/Berlin
      # - CLI_ARGS=
    volumes:
      - config:/config
      - /media/BACKUP1:/backup1 # Change to a external disk
      - /media/BACKUP2:/backup2 # Change to a external disk
      - /media/DATA:/source # All docker containers configuration

volumes:
  config:
