version: "3"

services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: Vaultwarden
    restart: always
    ports:
      - 8000:80
    environment:
      DOMAIN: "https://vault.x.com"
      ADMIN_TOKEN: ${ADMIN_TOKEN}
    volumes:
      - /media/DATA/Vaultwarden:/data/