version: "3"

services:
  mariadb:
    image: mariadb:latest
    container_name: MariaDB
    restart: always
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    volumes:
      - mariadb:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    env_file:
      - .env

  redis:
    image: redis:latest
    container_name: Redis
    restart: always
    command: redis-server --requirepass ${REDIS_HOST_PASSWORD}
    env_file:
      - .env

  app:
    image: nextcloud:latest
    container_name: App
    restart: always
    ports:
      - 88:80
    volumes:
      - nextcloud:/var/www/html
      - nextcloud-apps:/var/www/html/custom_apps
      - nextcloud-config:/var/www/html/config
      - nextcloud-data:/var/www/html/data
    environment:
      - NEXTCLOUD_ADMIN_USER=${NEXTCLOUD_ADMIN_USER}
      - NEXTCLOUD_ADMIN_PASSWORD=${NEXTCLOUD_ADMIN_PASSWORD}
      # - NEXTCLOUD_DATA_DIR=/media/
      - NEXTCLOUD_TRUSTED_DOMAINS=localhost
      # - TRUSTED_PROXIES=reverse-proxy
      # - OVERWRITEPROTOCOL=https
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_HOST=mariadb
      - REDIS_HOST=redis
      - REDIS_HOST_PASSWORD=${REDIS_HOST_PASSWORD}
    depends_on:
      - mariadb
      - redis
    env_file:
      - .env

volumes:
  mariadb:
  nextcloud:
  nextcloud-apps:
  nextcloud-config:
  nextcloud-data:
    # external: true
