version: "3"

services:
  mariadb:
    image: mariadb:latest
    container_name: MariaDB
    restart: always
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    volumes:
      - mariadb:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    env_file:
      - .env

  redis:
    image: redis:latest
    container_name: Redis
    restart: always
    command: redis-server --requirepass ${REDIS_HOST_PASSWORD}
    env_file:
      - .env

  app:
    image: nextcloud:latest
    container_name: App
    restart: always
    ports:
      - 88:80
    volumes:
      - /media/DATA/NextCloud:/var/www/html/data
      - main:/var/www/html
      - config:/var/www/html/config
      - apps:/var/www/html/custom_apps
    environment:
      - NEXTCLOUD_ADMIN_USER=${NEXTCLOUD_ADMIN_USER}
      - NEXTCLOUD_ADMIN_PASSWORD=${NEXTCLOUD_ADMIN_PASSWORD}
      # - NEXTCLOUD_DATA_DIR=/media/
      - NEXTCLOUD_TRUSTED_DOMAINS=server.local x.com
      - TRUSTED_PROXIES=reverse-proxy
      - OVERWRITEPROTOCOL=https
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_HOST=mariadb
      - REDIS_HOST=redis
      - REDIS_HOST_PASSWORD=${REDIS_HOST_PASSWORD}
    depends_on:
      - mariadb
      - redis
    env_file:
      - .env

  reverse-proxy:
    image: jc21/nginx-proxy-manager:latest
    container_name: Reverse-Proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
      - "81:81"
    volumes:
      - nginx-proxy-manager-data:/data
      - letsencrypt:/etc/letsencrypt

volumes:
  main:
  config:
  apps:
  mariadb:
  nginx-proxy-manager-data:
  letsencrypt:
