version: "3"
services:
  ouroboros:
    image: pyouroboros/ouroboros
    container_name: Ouroboros
    restart: always
    hostname: ouroboros
    environment:
      - CLEANUP=true
      - INTERVAL=300
      - LOG_LEVEL=info
      - SELF_UPDATE=true
      # - IGNORE=mongo influxdb postgres mariadb
      - TZ=Europe/Berlin
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
