version: "3.1"

services:
  mongo:
    image: mongo:latest
    container_name: MongoDB
    restart: always
    ports:
      - 17027:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongodb-data:/data/db

  # Credentials: admin:pass
  mongo-express:
    image: mongo-express:latest
    container_name: MongoExpress
    restart: always
    ports:
      - 17028:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_SERVER: mongo
      # ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:17027/

volumes:
  mongodb-data:
