version: "3"

services:
  postgresql:
    image: postgres:latest
    container_name: PostgreSQL
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: changeme
      POSTGRES_PASSWORD: notsecure
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgresql:/var/lib/postgresql/data/pgdata

  odoo:
    image: odoo:latest
    depends_on:
      - postgresql
    container_name: Odoo
    environment:
      HOST: postgresql
    restart: always
    ports:
      - 888:8069
    volumes:
      - odoo:/var/lib/odoo

volumes:
  odoo:
  postgresql:
