version: "3"

services:
  redis_db:
    image: "redis:alpine"
    container_name: Redis-Alpine
    restart: always
    ports:
      - 6379:6379
    command: redis-server
    # volumes: # No persistent data
    #   - ./redis-data:/data

  db:
    image: postgres:14
    container_name: Postgres-14
    restart: always
    ports:
      - 7432:5432
    command: postgres -c 'max_connections=200'
    environment:
      POSTGRES_PASSWORD: ""
      POSTGRES_USER: "postgres"
      POSTGRES_HOST_AUTH_METHOD: "trust"
    # volumes: # No persistent data
    #   - ./blockscout-db-data:/var/lib/postgresql/data/

  blockscout:
    depends_on:
      - db
      - redis_db
    image: blockscout/blockscout:${DOCKER_TAG:-latest}
    pull_policy: always
    restart: always
    stop_grace_period: 5m
    container_name: Blockscout
    links:
      - db:database
    command: bash -c "bin/blockscout eval \"Elixir.Explorer.ReleaseTasks.create_and_migrate()\" && bin/blockscout start"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - .env
    environment:
    # By default works with HardHat (7545), uncomment to use Ganache
      # ETHEREUM_JSONRPC_VARIANT: "ganache"
      # ETHEREUM_JSONRPC_HTTP_URL: http://host.docker.internal:8545/
      # ETHEREUM_JSONRPC_WS_URL: ws://host.docker.internal:8545/
      # INDEXER_DISABLE_INTERNAL_TRANSACTIONS_FETCHER: "true"
      # CHAIN_ID: "1337"
      # NETWORK: Ganache
    # --------------------------------------------------------------
      INDEXER_DISABLE_PENDING_TRANSACTIONS_FETCHER: "true"
      DATABASE_URL: postgresql://postgres:@host.docker.internal:7432/blockscout?ssl=false
      ECTO_USE_SSL: "false"
      SECRET_KEY_BASE: "56NtB48ear7+wMSf0IQuWDAAazhpb31qyc7GiyspBP2vh7t5zlCsF5QDv76chXeN"
    ports:
      - 4000:4000
    # volumes: # No persistent data
    #   - ./logs/:/app/logs/

# Custom Ganache version
# https://github.com/blockscout/blockscout/tree/master/docker-compose