version: "3"

services:
  jellyfin:
    image: linuxserver/jellyfin:latest
    container_name: Jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      # - JELLYFIN_PublishedServerUrl=192.168.0.5 #optional
    volumes:
      - jellyfin-config:/config
      - ${MEDIA}:/data
    ports:
      - 8096:8096
      # - 8920:8920 #optional
      - 7359:7359/udp #optional
      # - 1900:1900/udp #optional
    restart: unless-stopped

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qBittorrent
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/Berlin
      - WEBUI_PORT=8081
    volumes:
      - qbittorrent-config:/config
      - ${MEDIA}:/downloads
    ports:
      - 8081:8081
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped

  file-browser:
    image: filebrowser/filebrowser:latest
    container_name: FileBrowser
    ports:
      - 8:80
    volumes:
      - ${MEDIA}:/srv # directory to mount
      - ./filebrowser.db:/database.db
    security_opt:
      - no-new-privileges:true
    user: 1000:1000
    restart: unless-stopped

volumes:
  jellyfin-config:
  qbittorrent-config:
